<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use AppBundle\Helper\DateHelper;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	
	
	public function getUserByRole($role)
	{
		$result =  $this->createQueryBuilder()
		->addSelect('u')
		->where('u.role LIKE :roles')
		->setParameters('roles', '%"'.$role.'"%')
		->getQuery()->getResult();
		
		return $result;
	}
}