<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use AppBundle\Helper\DateHelper;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	/**
	* Récupère la liste des utilisateurs en leur adjoignant la totalité de leurs congés restants
	*/
	function findUserInfosWithLS()
	{
		$result =  $this->createQueryBuilder('u')
			->addSelect('lm')
			->join('u.userLeaveMonths', 'lm')
			->where('(ld.leaveStatus = 1 or ld.leaveStatus = 2) and u.id=lm.user_id and u.enabled=1')
			->getQuery()->getResult();
		
		return $result;
	}
}